image:
  root:
    path: /usr/blog/image
  default:
    album:
      id: 1
music:
  root:
    path: /usr/blog/music

server:
  port: 8082
jwt:
  secret: ghbsgasrfqwe_fsdfasdfasqwer12345sdf
  expiration: 3600
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.108.171.144:3306/blog?serverTimezone=Asia/Shanghai&useUnicode=true&useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=utf-8
    username: root
    password: bl.264979
  jackson:
    time-zone: Asia/Shanghai
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      write-date-keys-as-timestamps: false
  cache:
    redis:
      time-to-live: 3600
  data:
    redis:
      host: 47.108.171.144
      password: 264979
      port: 6379
      timeout: 2000


logging:
  level:
    root: info
